AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  # Loan payment financial function
  PMT:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'lambda_handlers.pmt_handler'
      CodeUri: '../code'
      Runtime: 'python3.6'
      Timeout: 30
      MemorySize: 256
