AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  # Wrapper function for all financial functions
  WRAPPER:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'wrapper_handler.financial_functions_handler'
      CodeUri: '../financial_functions'
      Runtime: 'python3.8'
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          LOG_LEVEL: INFO
