AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  # Internal Rate of Return for a schedule of cash flows that is not necessarily periodic
  XIRR:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'lambda_handlers.xirr_handler'
      CodeUri: '../financial_functions'
      Runtime: 'python3.6'
      Timeout: 30
      MemorySize: 256
